language: node_js
node_js:
- 5.10.1
addons:
  apt:
    packages:
    - sshpass
install:
- npm install
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  app: orlando-street-art
  api_key:
    secure: vW8SNOYyxeX/EoXovtlwZIU5aW5E6FaLHNAu4YcLDZarnxfr7x7jBbGz75Wt8xJE7gnsDEzbQwhBtxOMv7udY72IRH4L02WnzKmOOXCW5UGZuhhQGbjRnRGaFoq7HveY1osHb3bDw3DwLu8NZcQ1g6gZeWWRGAdANzGnFXKXbHVJL/1XIU8Rda1ntF9vPhkhgKxVKVCB0g6xy2D7ykjO3PyXkbZd3wfaO4PhibseXhbAFITOtdR17eDEOES2s+YxA2SgayR/G6pE9N2Gfop00AFw21ey+IERhcFVUQtwqYatrPX45Sxa1Tmc9iUomq2WN9QDnjcTFfVSZSW+QWSGdl1mrW7QJnP7C0p06rDxSDYWgOHh+a55Iy8i6ThrD1X0koZuWSRqaNaoUx2H3SEPqIiYvfBueiih94jV4Hw9irQQlHp5DpdJi5oEsMw/sDh9mCzfjg7ljz5+gl/5DTRE0882WIagEiF4Uzm168rpGcL6F8LIx+6oKM2bylLb1GJ66vE+soAccemLQ5UcSkodkFep6wbITGMm7Fi2dTN4H6oZUZdmKUsnWTIjzQBjccS5L2ZGozAzIgncbS1l8CcdvvX+243Ucov/C1XBxP31n0sssYCZ+2nDnpQUJl1E2M0ARsnMBUfOtuyXWeJNfTxvNksued2++2P/J5CvPigZtko=
  on:
    repo: grailian/street-art-orlando-web
    branch: master
